/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://6oxuu47mvva7boblfejjgolykm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lzav6waoajg2tfdj2rmfxtwq3i",
    "aws_cognito_identity_pool_id": "us-east-1:ba56defd-9d95-40ba-9d4d-7ce428db475f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_atojPZgCK",
    "aws_user_pools_web_client_id": "4jhjqhum512ifn9aakleha0l52",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "rentto-dev-storage-6028e19594933-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
